# Generated by Django 4.2.1 on 2023-06-08 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPBL5', '0002_alter_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license_plate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_plates', to='appPBL5.user'),
        ),
    ]
