# Generated by Django 4.2.1 on 2023-06-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPBL5', '0003_alter_license_plate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking_history',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='parking_history',
            name='price',
        ),
    ]
