# Generated by Django 4.2.1 on 2023-06-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPBL5', '0005_user_identity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity_code',
            field=models.CharField(default='N', max_length=100),
        ),
    ]
