# Generated by Django 4.2.1 on 2023-06-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPBL5', '0007_alter_user_identity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_history',
            name='check_out_time',
            field=models.DateTimeField(null=True),
        ),
    ]
